---
name: Site Name Here
url: http://example.com
author:
  name: Author Name here
  email: yourname@exmaple.com
tags:
  - kizz
  - github
  - jade
comments: null
tracker: null
plugins:
  - kizz-markdown
  - kizz-guess-tags-en
  - kizz-guess-title
registry: https://registry.npm.taobao.org
theme: kizz-theme-paper
log:
  - log
  - debug
  - error