---
name: Site Name Here
url: http://example.com
author:
  name: Author Name here
  email: yourname@exmaple.com
tags:
  - kizz
  - github
  - jade
comments: null
tracker: null
plugins:
  - /home/zenozeng/code/kizz-markdown
  - /home/zenozeng/code/kizz-guess-tags-en
registry: https://registry.npm.taobao.org
theme: theme/
log:
  - log
  - debug
  - error