---
name: Site Name Here
url: http://example.com
author:
  name: Author Name here
  email: yourname@exmaple.com
tags:
  - kizz
  - github
  - jade
  - 博客
comments: null
tracker: null
plugins:
  - kizz-markdown
  - kizz-guess-tags
theme: kizz-theme-paper
log: debug
