---
name: Site Name Here
url: http://example.com
author:
  name: Author Name here
  email: youname@exmaple.com
tags:
  - kizz
  - github
  - jade
comments: null
tracker: null
plugins:
  - compiler-cache
  - markdown
  - guess-tags-en
  - file-diff
  # get file diff, calc targets via routes and delete files removed
  # diff between last compile.
  # note the routes must be sure, so this plugin should be put at last
  # if any plugins change the routes, that plugin should be put before it
